###
GET http://localhost:3003/ HTTP/1.1

###
GET http://localhost:3003/api/blogs HTTP/1.1

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "firstDay",
  "author": "Will",
  "url": "http://localhost:3003/",
  "likes": 69
}